class SportCenter {
  String centerid,
      centername,
      centerphone,
      centerlocation,
      centerlatitude,
      centerlongitude,
      centeropentime,
      centerclosetime,
      centerprice,
      centeroffday,
      centerremarks,
      centerimage,
      useremail;
  SportCenter(
      {this.centerid,
      this.centername,
      this.centerphone,
      this.centerlocation,
      this.centerlatitude,
      this.centerlongitude,
      this.centeropentime,
      this.centerclosetime,
      this.centerprice,
      this.centeroffday,
      this.centerremarks,
      this.centerimage,
      this.useremail});
}
